### PR TITLE
Update the parser for the latest Revolut CSV format

### PR DESCRIPTION
**Pull request by ndfred**
Changes the header format (no more spaces), dates are now "September 10" and "2018 August 28" instead of "Apr 8, 2018"
Added a unit test

### CODE REVIEW

**Comment by mlaitinen** [comment]
Thanks for the PR!

I just exported my bank statement for September 2019 and the header format is the following:
```
Completed Date ; Description ; Paid Out (EUR) ; Paid In (EUR) ; Exchange Out; Exchange In; Balance (EUR); Category; Notes
```
And my date format is still `Sep 28, 2019`.
Which version of the Revolut app you're using? I'm using the Android app version 6.10.

Also, the date format can be configured in the ofxstatement configuration by specifying `date_format`.

**Comment by ndfred** [comment]
This is actually from the iOS app, just tested again on version 6.10 (Euro account) and my header looks like this:

    Completed Date;Reference;Paid Out (EUR);Paid In (EUR);Exchange Out;Exchange In; Balance (EUR);Category

For the date format, it is really confusing: they are using one format for the current year (omitting the year effectively), and another one for the past years (which do mention it). I put both formats in the test case data. I also kept backwards compatibility so that shouldn't affect the other statements formats (which appear to be Android formats rather than older formats).

**Comment by ndfred** [comment]
A couple issues I've seen today (may not be related to this PR):

* top ups fill in the Memo field but not the Payee field
* processing a GBP statement chokes on a parsing error

I'll try and get these fixed.

Update: the GBP statement crashes while parsing because Revolut didn't escape a ";" value in a payee, so nothing on ofxstatement's end (the file format is simply invalid).

**Comment by ndfred** [comment]
@mlaitinen: any chance we could get this merged? The reason I've been overriding `parse_datetime` is that it is the only way I have found to handle the three different date formats (Android, iOS, iOS from years past). Happy to hear suggestions there.

**Comment by mlaitinen** [comment]
Sorry, I was expecting a notification after you were finished with the issues.

I can't get your unit test to pass. There might be something peculiar in my environment, but could you double check if it runs in your environment?

**Comment by ndfred** [comment]
This is what I get from running it locally:

```
$ cd src/ofxstatement/tests
$ python3 -m unittest
/usr/local/lib/python3.7/site-packages/ofxstatement/configuration.py:23: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
  config = configparser.SafeConfigParser()
./usr/local/lib/python3.7/site-packages/ofxstatement/configuration.py:23: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
  config = configparser.SafeConfigParser()
./usr/local/lib/python3.7/site-packages/ofxstatement/configuration.py:23: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
  config = configparser.SafeConfigParser()
/Users/fred/Code/ofxstatement-revolut/src/ofxstatement/tests/test_revolut.py:50: ResourceWarning: unclosed file <_io.TextIOWrapper name='/Users/fred/Code/ofxstatement-revolut/src/ofxstatement/tests/samples/2019-september.csv' mode='r' encoding='utf-8'>
  output=output.name,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
.
----------------------------------------------------------------------
Ran 3 tests in 0.088s

OK
```

The [CI run](https://travis-ci.com/mlaitinen/ofxstatement-revolut/jobs/237947197) also logs three successful test runs so I guess we are good. What does it look like on your machine?

**Comment by mlaitinen** [comment]
Sorry, my bad :) Looks like I ran the tests with the old code (=old column headers). It works now.

Thanks for the contribution!

**Comment by ndfred** [comment]
Thanks for the review!

**Pull request merged**
