### PR TITLE
Add “Payment from “ option in TRANSACTION_TYPES

### PR DESCRIPTION
**Pull request by zanderle**
`Payment from ` should also count as a deposit.

### CODE REVIEW

**Comment by mlaitinen** [comment]
Thanks for the PR! I'm happy to see that this plugin is useful for others as well.

You probably have to add a dependency to the currency converter. I get 
```
Traceback (most recent call last):
  File "/usr/local/bin/ofxstatement", line 11, in <module>
    load_entry_point('ofxstatement==0.6.2.dev1', 'console_scripts', 'ofxstatement')()
  File "/usr/local/lib/python3.6/dist-packages/ofxstatement-0.6.2.dev1-py3.6.egg/ofxstatement/tool.py", line 151, in run
  File "/usr/local/lib/python3.6/dist-packages/ofxstatement-0.6.2.dev1-py3.6.egg/ofxstatement/tool.py", line 121, in convert
  File "/usr/local/lib/python3.6/dist-packages/ofxstatement-0.6.2.dev1-py3.6.egg/ofxstatement/plugin.py", line 15, in get_plugin
  File "/home/mlaitinen/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2321, in load
    return self.resolve()
  File "/home/mlaitinen/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2327, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/ofxstatement_revolut-1.2.0-py3.6.egg/ofxstatement/plugins/revolut.py", line 4, in <module>
ModuleNotFoundError: No module named 'currency_converter'
```

Also, please don't change the date format. I'm aware it should be made configurable, like mentioned in #3. I'll see if I have time to do that, or if someone else would like to do it.

**Comment by zanderle** [comment]
Hm, let me check again. I made some additional changes to my fork, but those weren’t meant to be merged... maybe I didn’t push the changes to the branch I intended so now you’re also seeing those.

I’ll check later and remove all this custom stuff that shouldn’t be merged in the first place 😊

**Comment by mlaitinen** [comment]
Ahh yes, it's the master branch. Makes sense now.

You might want to pull my master. I just implemented the date format setting.

**Comment by mlaitinen** [comment]
I cherry-picked the commit from your branch to the master. Thanks :+1:

**Pull request closed without merging**
